### ISSUE TITLE
Open source Algorand projects

### ISSUE THREAD

**Issue by Pfed-prog** [awesome-algorand/awesome-algorand#163]
**Is your feature request related to a problem? Please describe.**
I have built a bunch of popular project with Algorand smart contracts and indexer but there is no alley to promote them.

**Describe the solution you'd like**

Please create a section for open-source projects

**Additional context**

https://github.com/dspytdao/Algo_AMM 

The application allows you to trade on the outcomes of events, and follow the odds to garner accurate insights about the future. Users buy or sell Voting Shares, which can be redeemed for 1 unit of the stable asset if the outcome is resolved as correct, and become worthless if it’s incorrect.

https://github.com/dspytdao/AlgoDepo

Single Deposit App Algorand

**Comment by aorumbayev** [comment]
Hey @Pfed-prog, thanks for opening the issue, most of the urls on the README are open source. Feel free to open PRs under categories that you see your tooling fit the best and I'll make sure to review and merge 👍
